### ISSUE TITLE
Shabby deltagersøk

### ISSUE THREAD

**Issue by thusoy** [UKMNorge/UKMresponsive#27]
Testcase: Deltager "Eline W. Ghost". Søk etter "Eline Ghost" gir ingen resultater.

**Comment by AsgeirSH** [comment]
Note: Mitt custom fastlivefilter (som brukes i UKMNorge/UKMDelta#231) ville håndtert dette - men her er det kanskje snakk om søk direkte i databasen? @mariusmandal

**Comment by thusoy** [comment]
😳
