### ISSUE TITLE
Illustrasjonsbilde i safari

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMresponsive#28]
Illustrasjonsbilder i safari kan finne på å bli litt sammenklemt (vises ikke i full høyde). Skaleringsbug css?

**Comment by mariusmandal** [comment]
Gjelder når man er inne på et innlegg

**Comment by AsgeirSH** [comment]
Unable to reproduce - mulig fiksa med WP-update til 4.4.2?

**Comment by mariusmandal** [comment]
Samme her. Close
