### ISSUE TITLE
Sett riktig twig cache path

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMresponsive#41]
Vagrant-versjonen må nå opprette mappen /home/ukmno/public_html/cache_twig/ for at UKMresponsive skal kunne cache (og virke).

https://github.com/UKMNorge/UKMresponsive/blob/master/index.php#L19

**Comment by AsgeirSH** [comment]
define('TWIG_CACHE_PATH', sys_get_temp_dir().'/cache_twig/');

Ser ut til å funke greit i vagrant, gir = /tmp/cache_twig/
