### ISSUE TITLE
Automatiser JS + CSS-minify

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMresponsive#42]
I dag brukes codekit for å gjøre dette. Burde integreres i koden på en måte slik at det skjer automatisk

**Comment by AsgeirSH** [comment]
Kan _IKKE_ gjøres fra Cloudflare fordi vi også må kompilere LESS. (-.-)

**Comment by AsgeirSH** [comment]
Skrevet /home/ukmno/private_shell/UKMresponsive_less.sh som kompilerer LESS, inkl. minified. 
Trigges fra public_subdomains/git/index.php. Den bør også trigge JS-minify og Cloudflare-cache-rebuild.

**Comment by AsgeirSH** [comment]
UKMresponsive_less.sh kompilerer LESS og trigger en cloudflare-cache-rebuild av den filen. Minify tar Cloudflare seg av. Close.
