### ISSUE TITLE
Multi-author + tittel

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMresponsive#5]
[ ] Integrer multi-author-plugin
[ ] Integrer visning multi-author
[ ] Få inn tittel på author

**Comment by AsgeirSH** [comment]
Lag som en admin-tweak-box (kalt "Bidragsytere"?):
Dropdown over alle med rettigheter til bloggen, og input-felt med rolle. Legg til-knapp, og kryss for å fjerne.
Lagring: Lagre author-id og rolle i et array, serialize det i et meta-felt kalt ukm_ma (UKM Multi-Author). Kan da enkelt leses ut og deserializes, vil jeg tro?

Men hvordan presentere bidragsyterne best mulig i artikkelen? Kan jo ikke vise bildet til alle, det tar fort for mye oppmerksomhet.

**Comment by AsgeirSH** [comment]
Fixed in c3be987 og UKMNorge/UKMwp_admin_tweaks@1bb93452c3e9be104b9cfee48c41eebd038ab2b3 -> UKMNorge/UKMwp_admin_tweaks@b8de42c4cd3b5bb9a521aa15177699be147c0d08. Close.
