### ISSUE TITLE
"Ser du etter 20xx-sidene" viser feil år

### ISSUE THREAD

**Issue by AsgeirSH** [UKMNorge/UKMresponsive#63]
Når vi har bikket 2016 viser new_season.twig.html feil år. Se Freshdesk 447.

**Comment by mariusmandal** [comment]
Skal mest sannynlig gjelde kun festivalsiden, og skjer fordi monstring.starter is not defined (uten at jeg skjønner hvorfor…) Kan den mangle i databasen? (usannsynlig)


Mvh,


Marius Mandal

92837360

mariusmandal@gmail.com


—Sent from Mailbox

**Comment by AsgeirSH** [comment]
Ingen fylkesmønstringer eller festivalen mangler pl_stop, pl_start eller deadlines, annet enn gjester og testfylke. Men vi sender jo ikke inn monstring-objektet i embed'en, så det er mulig det blir noe kødd der? (at den alltid tar 'now' uansett hva?)

**Comment by AsgeirSH** [comment]
Fixed in 9b605c3. Close.
