### ISSUE TITLE
Bytt ut meny-bildet med FB-mini-thumbnail?

### ISSUE THREAD

**Issue by AsgeirSH** [UKMNorge/UKMresponsive#65]
Usikker på om dette gjelder hele UKMresponsive eller bare UKMdeltas lokale overstyring.

**Comment by mariusmandal** [comment]
Say what?



Mvh,


Marius Mandal

92837360

mariusmandal@gmail.com


—Sent from Mailbox

**Comment by AsgeirSH** [comment]
Sendt fra min iPad

**Comment by AsgeirSH** [comment]
Lol, hvor ble det av bildet jeg limte inn her?

**Comment by AsgeirSH** [comment]
![image](https://cloud.githubusercontent.com/assets/1831028/12917644/d9521906-cf3a-11e5-9fcc-65ee067d323f.png)

**Comment by AsgeirSH** [comment]
![image](https://cloud.githubusercontent.com/assets/1831028/12917648/e7a54424-cf3a-11e5-9d49-10f00ee95117.png)

**Comment by mariusmandal** [comment]
etter forklaring fra @AsgeirSH: bytt ut ninjaen med facebook profilbilde hvis koblet til facebook
