### ISSUE TITLE
Info om mønstringen

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMresponsive#67]
Vi må få frem info om mønstringen på en bedre måte
- bedre visning av dato + tidspunkt
- visning av påmeldingsfrister (som i dag er helt borte (edit: neida, men point made))
- menyvalg for påmelding (#66)

Hvis dato og menyvalg for "program" kan stå i umiddelbar nærhet av hverandre er det meget fint

**Comment by AsgeirSH** [comment]
Gjort m/ påmeldingsfrist-flytt.
Close
