### ISSUE TITLE
Opengraph image feiler på facebook

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMresponsive#68]
Deling av lenker på facebook gir logo og ikke artikkelbilde. Må fikses så man kan velge blant featured image / alle bilder i artikkelen. I alle fall ikke kun logo

https://github.com/UKMNorge/UKMresponsive/blob/356f8ae2267ea87c97a60ae9728e765e7574b566/twig/element/seo.twig.html

**Comment by AsgeirSH** [comment]
Unable to replicate. Funker både med Share-knappen og med liming av URL direkte i facebook-status nå. 

Mulig Cloudflare ikke slapp gjennom FB-linteren, ref. Marius åpnet noe tidligere?

FB-debugger viser alt relatert til denne delingen ok: https://developers.facebook.com/tools/debug/og/object?q=http%3A%2F%2Fukm.no%2Fsor-trondelag%2F2016%2F02%2F01%2Fikke-noe-press-om-a-vaere-best%2F

Close.
